---
format: 
  elsevier-html: default
  elsevier-pdf:
    keep-tex: true
    journal:
      name: Journal Name
      formatting: preprint
      model: 3p
      cite-style: super

editor: visual
title: |
  DNA metabarcoding diet analysis in reindeer is quantitative 
  and integrates feeding over several weeks

# if short-title is defined, then it's used
short-title: Ouups
bibliography: bibliography/bibliography.bib
copyright: 
  holder: Reinin project
  year: 2024
author:
  - name: Stefaniya Kamenova
    email: stefaniya.kamenova@gmail.com
    attributes:
      corresponding: true
    orcid: 0000-0002-7241-0506
    affiliations:
      - ref: cees
      - ref: denrm
      - ref: nmhmsofia
  - name: Pernille Meyer
    affiliations:
      - ref: cees
  - name: Anne Krag Brysting
    affiliations:
      - ref: cees
  - name: Leo Rescia
    affiliations:
      - ref: damb
  - name: Lars P. Folkow
    affiliations:
      - ref: damb
  - name: Galina Gusarova
    email: galina.gusarova@uit.no
    role: "Equal contribution"
    affiliations:
      - ref: cees
      - ref: damb
      - ref: aumn
      - ref: dbsp
  - name: Eric Coissac
    email: eric.coissac@metabarcoding.org
    role: "Equal contribution"
    orcid: 0000-0001-7507-6729
    affiliations:
      - ref: leca

affiliations:
  - id: cees
    name: |
      Centre for Ecological and Evolutionary Synthesis, 
      University of Oslo
    city: Oslo
    country: Norway
  - id: denrm
    name: |
      Departments of Ecology and Natural Resource Management, 
      Norwegian University of Life Sciences
    city: Ås
    state: Norway
  - id: nmhmsofia
    name: |
      National Museum of Natural History,
      Bulgarian Academy of Sciences
    city: Sofia
    state: Bulgaria
  - id: damb
    name: |
      Department of Arctic and Marine Biology, 
      The Arctic University of Norway
    city: Tromsø
    state: Norway
  - id: aumn
    name: |
      The Arctic University Museum of Norway, 
      The Arctic University of Norway
    city: Tromsø
    state: Norway
  - id: dbsp
    name: |
      Department of Botany, 
      St Petersburg State University
    city: St Petersburg
    state: Russia
  - id: leca
    name: |
      Laboratoire d'Ecologie Alpine, 
      CNRS, Université Grenoble Alpes
    city: Grenoble
    state: France
    
abstract: |
  Dietary DNA metabarcoding is an established method, especially useful for resolving the 
  diverse diets of large mammalian herbivores (LMH). However, despite longstanding research
  interest on the topic, we still lack unequivocal evidence on the potential of 
  DNA metabarcoding to reflect proportions of ingested dietary plants in LMH. One major aspect 
  to consider is the time window during which ingested diet remains detectable in faecal 
  samples. This parameter is currently unknown for LMH, thus potentially hindering the scope 
  of ecological conclusions. Another unknown factor is quantitative performance, i.e. the 
  extent to which the amount of ingested biomass can be assessed based on sequence reads 
  abundances. We assessed DNA metabarcoding, quantitative performance and DNA half-life 
  detectability for plants with different digestibilities in a controlled feeding experiment 
  with three female Eurasian tundra reindeer (Rangifer tarandus tarandus). Reindeer were fed 
  birch twigs (Betula pubescens) and increasing biomass of lichen (mainly Cladonia stellaris). 
  Relative reads abundance positively correlated with ingested lichen biomass, suggesting 
  potential for deriving dietary proportions in free-ranging reindeer on natural pasture.
  Dietary DNA was consistently detected within a few hours upon ingestion, with a mean 
  half-life detectability of 25 and 16 hours for birch and lichen, respectively. However, 
  dietary DNA remained detectable in faeces for at least 26 days post-feeding, indicating 
  that a single faecal sample can provide an unsuspectedly integrative estimate of diet in 
  ruminants. Together, our findings provide novel empirical validation of DNA metabarcoding as 
  a tool for diet analysis in LMH.
---

# Github project

Every script and processed data are available from the RENIN-Project/Feeding-Experiment github project.

-   <https://github.com/RENIN-Project/Feeding-Experiment>

# Preprocessing of the raw data

The [`OBITools`](http://metabarcoding.org/obitools) commands used to preprocess the data from the raw FASTQ files are described in the following bash script.

-   [Bash script for the preprocessing of the raw data](obitools_processing.sh)

# Filtering of the data

-   For the *Spermatophyta* [`Sper01`](SPER01_filtering.html) marker
-   For the *Eukaryota* [`Euka02`](EUKA02_filtering.html) marker

# Ecological analysis

Every code producing the presented results including the production of the figures is available [here](alpin_algeaes.html)

# Processed data sets and results

Each processed dataset is composed of three coma separated values files (`.csv` files).

-   For the *Spermatophyta* `Sper01` marker
    -   The MOTUs description file : [`FE.Spermatophyta.samples.motus.csv`](Data/Faeces/FE.Spermatophyta.samples.motus.csv)
    -   The samples description file : [`FE.Spermatophyta.samples.samples.csv`](Data/Faeces/FE.Spermatophyta.samples.samples.csv)
    -   The reads contengency table : [`FE.Spermatophyta.samples.reads.csv`](Data/Faeces/FE.Spermatophyta.samples.reads.csv)
-   For the *Eukaryota* `Euka02` marker
    -   The MOTUs description file : [`Euka03.cleaned.motus.csv`](cleaned_datasets/Euka03.cleaned.motus.csv)
    -   The samples description file : [`Euka03.cleaned.samples.csv`](cleaned_datasets/Euka03.cleaned.samples.csv)
    -   The reads contengency table : [`Euka03.cleaned.reads.csv`](cleaned_datasets/Euka03.cleaned.reads.csv)
